default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: valentines_api_development

test:
  <<: *default
  database: valentines_api_test

production:
  <<: *default
  database: valentines_api_production
  username: valentines_api
  password: <%= ENV['VALENTINES_API_DATABASE_PASSWORD'] %>
